### ISSUE TITLE
What is the supposed behavior of the 'spawn' function?

### ISSUE THREAD

**Issue by Twix53791** [hXtreme/suckless-tabbed#1]
Hi, I take advantage to this question to thank you for posting your build ! I tried in vain to patch tabbed with hidetabs before finding your repo, probably something wrong with the 'official' config.mk in my desktop environment. Anyway, everything works fine, except the 'spawn' function which seems not working. Nothing related to your build, I have got the same behavior with tabbed from AUR repo. It is not supposed to create an empty tab? Or duplicate one? I use tabbed with applications like zathura, nomacs, libreoffice, maybe this behavior only works in surf or some apps like that?

Thank you again for your dotfiles!

**Comment by hXtreme** [comment]
The spawn function forks a child process and in the child process it runs the command (in this case surf) passing in any arguments you specified.


The issue might actually be with surf, are you able to run surf without tabbed?

If you aren't able to run surf then l recommend uninstalling surf, then go to the /usr/local/lib and delete the surf directory if it exists. After this install surf and try again.

**Comment by Twix53791** [comment]
OK. No, in fact, I don't use tabbed with surf ; I don't use surf (for now). I use tabbed to tab application like libre office, zathura, nomacs, well... things I use. How can I pass command to the spawn function? I say that, but I am not sure I need this behavior, as I made [a script](https://github.com/Twix53791/bsp-tabapp) which runs automatically the new windows of these apps into the same tabbed instance... So it is like opening a new tab from outside. But... for example if I could launch a command in a 'new tab', I could launch fzf into every new tab by default, for example to select a file to open in tabbed... It would be really amazingly smooth and perfect ! haha

**Comment by hXtreme** [comment]
spawn executes when you press Ctrl + Enter.

See the man page for tabbed to see how to pass it a command to execute it has a bunch of examples that can help you.

**Comment by Twix53791** [comment]
I found ! The man page was a bit cryptic until now for me, but pushed by the necessity, I figured out. I leave here the tips for the vast people of noobies I am part of : 
1) To run a command in tabbed, you have to spawn a terminal and use -e or bash -c option for example to run a command into the terminal
2) Not every terminal will work, as it needs the possibility to be embedded into tabbed.
3) the -r flag is needed. Its meaning, if I guess well, is to send, here as 2th arg position, the tabbed window id. So in fact it is 'st -w tabbed.id, and probably xterm -into tabbed.id rest-of-args.
ex: 
`tabbed -r 2 st -w '' bash -c 'ls;sleep 3`
`tabbed -r 2 xterm -into -e fzf`

And... even better:
thanks to [this reddit post](https://www.reddit.com/r/suckless/comments/f8acgf/open_multiple_tabs_with_tabbed_each_of_them/), I understood the -d and -s flags. The -s flag prevent the "command" to be automatically spawned at start up, so only ctrl+enter will spawn it ; marvelous, but for a reason I ignore, it is not working if its just passed as an extra argument in the commands above. We need to use a syntax involving the -d argument:
`st -w $(tabbed -d -s -r 2 st -w -e fzf) ranger &` 

How it works? If i understand well, the command above run 'st ranger & into tabbed (-w argument), and this tabbed instance is run itself with the argument 'st -e fzf', into tabbed (-r 2 -w tabbed.id), BUT it will not execute this argument straightaway, thanks for the -s flag. The -d flag is needed to send the tabbed window id to the -w argument of the first st command ? I don't know, but I have now everything in hands to run a custom fzf menu into tabbed, and then do really fancy things !! :)

PS: In fact, `tabbed -s -r 2 st -w '' -e fzf &` can work if we reparent, after, a window to tabbed. Straightway there is at least one filled tab, the spawn function works.
